namespace Email_Notification
{
    class Program
    {
        static void Main(string[] args)
        {
            sendEmail();
        }
        public static void sendEmail()
        {
            
            MailMessage mailObj = new MailMessage();
            string subject = "  Interns Weekly Status -Reminder  ";
            mailObj.Subject =subject;
           
            string body = "<p>Dear All,</p><p><br></p><p>Make sure to upload the weekly status by EOD today at : <a href='https://wdc.app.box.com/folder/52868530687' target='_blank'>https://wdc.app.box.com/folder/64863107383</a>.</p><p><br></p><p><em style='color: rgb(31, 73, 125); font-size: 10pt;'>This email is AutoGenerated so please don't reply.</em></p>";
            mailObj.Body = body;



            List<dynamic> getAllRecipients = new List<dynamic>();
          //  getAllRecipients.Add("Vidyavachaspathi.Kabbinale@wdc.com");
            getAllRecipients.Add("Gagandeep.chugh@wdc.com");
            foreach (dynamic emailAddress in getAllRecipients)
            {
                mailObj.To.Add(emailAddress);
                
            }

            send(mailObj, null);
        }

        public static void send(MailMessage MailMessage, List<Attachment> Attachments = null)
        {
            string smtpServerUrl = "wdcrelay.wdc.com";
            int port = 25;
            SmtpClient client = new SmtpClient(smtpServerUrl, port);
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.UseDefaultCredentials = false;
            client.EnableSsl = false;
            MailMessage.From = new MailAddress("no-reply@wdc.com", "SWT");             if (Attachments != null)
            {
                foreach (Attachment Attachment in Attachments)
                {
                    MailMessage.Attachments.Add(Attachment);
                }
            }
            MailMessage.IsBodyHtml = true;
            MailMessage.Priority = MailPriority.High;

            //Task.Factory.StartNew(() =>
            client.Send(MailMessage);
            //);
        }
    }
}
